FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y python3-pip python3-dev software-properties-common curl && \
    apt-get install -y libz-dev pkg-config libtool m4 autotools-dev automake libncurses5-dev libbz2-dev liblzma-dev

RUN mkdir /tools

# install samtools 1.10
RUN cd /tmp \
    && curl -sSL -o samtools-1.10.tar.bz2 --retry 10 https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2 \
    && bunzip2 -c samtools-1.10.tar.bz2 |tar xf - \
    && cd samtools-1.10 \
    && ./configure --prefix=/usr/local \
    && make \
    && make install

# cramtools installation
# the current master has commit hash 0b5c9ece97dba616226405bec4a053e5b04c53d1
# using hash to protect us from potential future problems
RUN curl -sSL -o /tools/cramtools.jar --retry 10 https://github.com/enasequence/cramtools/blob/0b5c9ece97dba616226405bec4a053e5b04c53d1/cramtools-3.0.jar?raw=true

# install bwa
RUN cd /tmp \
    && curl -sSL -o v0.7.17.tar.gz --retry 10 https://github.com/lh3/bwa/archive/v0.7.17.tar.gz \
    && tar xzf v0.7.17.tar.gz \
    && cd bwa-0.7.17 \
    && make \
    && cp bwa /usr/bin/bwa

#Install libmaus2
ENV LIBMAUS_VERSION=2.0.698-release-20200203095315
ENV LIBMAUS_SOURCE=https://gitlab.com/german.tischler/libmaus2/-/archive/$LIBMAUS_VERSION/libmaus2-$LIBMAUS_VERSION.tar.gz
RUN cd /tmp \
    && curl -sSL -o libmaus2-$LIBMAUS_VERSION.tar.gz --retry 10 $LIBMAUS_SOURCE \
    && tar -zxvf libmaus2-$LIBMAUS_VERSION.tar.gz \
    && cd libmaus2-$LIBMAUS_VERSION \
    && libtoolize \
    && aclocal \
    && autoreconf -i -f \
    && ./configure \
    && make \
    && make install

#Install biobambam2
ENV BIOBAMBAM_VERSION=2.0.153-release-20200124123734
ENV BIOBAMBAM_SOURCE=https://gitlab.com/german.tischler/biobambam2/-/archive/$BIOBAMBAM_VERSION/biobambam2-$BIOBAMBAM_VERSION.tar.gz
RUN cd /tmp \
    && curl -sSL -o biobambam2-$BIOBAMBAM_VERSION.tar.gz --retry 10 $BIOBAMBAM_SOURCE \
    && tar -zxvf biobambam2-$BIOBAMBAM_VERSION.tar.gz \
    && cd biobambam2-$BIOBAMBAM_VERSION \
    && autoreconf -i -f \
    && ./configure --with-libmaus2=/usr/local/lib --prefix=/tools/biobambam2 \
    && make install

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Picard installation
RUN curl -sSL -o /tools/picard.jar --retry 10 https://github.com/broadinstitute/picard/releases/download/2.21.8/picard.jar

ENV LD_LIBRARY_PATH=/usr/local/lib

ENV PATH="/tools:/tools/biobambam2/bin:${PATH}"

CMD /bin/bash
