FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y python3-pip python3-dev software-properties-common curl && \
    apt-get install -y samtools libz-dev pkg-config libtool m4 autotools-dev automake

RUN mkdir /tools

RUN cd /tmp \
    && curl -sSL -o samtools-1.10.tar.bz2 --retry 10 https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2 \
    && tar xzf samtools-1.10.tar.bz2 \
    && cd samtools-1.10 \
    && ./configure --prefix=/usr/local/bin \
    && make \
    && make install

RUN cd /tmp \
    && curl -sSL -o v0.7.17.tar.gz --retry 10 https://github.com/lh3/bwa/archive/v0.7.17.tar.gz \
    && tar xzf v0.7.17.tar.gz \
    && cd bwa-0.7.17 \
    && make \
    && cp bwa /usr/bin/bwa

#Install libmaus2
ENV LIBMAUS_VERSION=2.0.611-release-20190408112550
ENV LIBMAUS_SOURCE=https://gitlab.com/german.tischler/libmaus2/-/archive/$LIBMAUS_VERSION/libmaus2-$LIBMAUS_VERSION.tar.gz
RUN cd /tmp \
    && curl -sSL -o libmaus2-$LIBMAUS_VERSION.tar.gz --retry 10 $LIBMAUS_SOURCE \
    && tar -zxvf libmaus2-$LIBMAUS_VERSION.tar.gz \
    && cd libmaus2-$LIBMAUS_VERSION \
    && libtoolize \
    && aclocal \
    && autoreconf -i -f \
    && ./configure \
    && make \
    && make install

#Install biobambam2
ENV BIOBAMBAM_VERSION=2.0.95-release-20190320141403
ENV BIOBAMBAM_SOURCE=https://gitlab.com/german.tischler/biobambam2/-/archive/$BIOBAMBAM_VERSION/biobambam2-$BIOBAMBAM_VERSION.tar.gz
RUN cd /tmp \
    && curl -sSL -o biobambam2-$BIOBAMBAM_VERSION.tar.gz --retry 10 $BIOBAMBAM_SOURCE \
    && tar -zxvf biobambam2-$BIOBAMBAM_VERSION.tar.gz \
    && cd biobambam2-$BIOBAMBAM_VERSION \
    && autoreconf -i -f \
    && ./configure --with-libmaus2=/usr/local/lib --prefix=/tools/biobambam2 \
    && make install

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Picard installation
RUN curl -sSL -o /tools/picard.jar --retry 10 https://github.com/broadinstitute/picard/releases/download/2.19.0/picard.jar

ENV LD_LIBRARY_PATH=/usr/local/lib

ENV PATH="/tools:/tools/biobambam2/bin:${PATH}"

CMD /bin/bash
